name: Run tests (lab5 + lab6)

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Upgrade pip
        run: |
          python -m pip install --upgrade pip

      - name: Install lab5 dependencies
        working-directory: lab5
        run: |
          pip install -r requirements.txt

      - name: Run lab5 API tests (jsonplaceholder)
        working-directory: lab5
        env:
          API_BASE_URL: https://jsonplaceholder.typicode.com
        run: |
          pytest -v

      - name: Install lab6 dependencies
        working-directory: lab6
        run: |
          pip install -r requirements.txt

      - name: Run lab6 unit tests
        working-directory: lab6
        run: |
          pytest -v

